name: learn-github-actions
on: [push]
jobs:
  one:
    runs-on: macos-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: PWD
        run: pwd
      - name: PWD
        run: ls -al
